# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wonder/UNP/summary/Server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wonder/UNP/summary/Server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wonder/UNP/summary/Server/CMakeFiles /home/wonder/UNP/summary/Server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wonder/UNP/summary/Server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named a.out

# Build rule for target.
a.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 a.out
.PHONY : a.out

# fast build rule for target.
a.out/fast:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/build
.PHONY : a.out/fast

agent.o: agent.c.o

.PHONY : agent.o

# target to build an object file
agent.c.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/agent.c.o
.PHONY : agent.c.o

agent.i: agent.c.i

.PHONY : agent.i

# target to preprocess a source file
agent.c.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/agent.c.i
.PHONY : agent.c.i

agent.s: agent.c.s

.PHONY : agent.s

# target to generate assembly for a file
agent.c.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/agent.c.s
.PHONY : agent.c.s

buffer.o: buffer.c.o

.PHONY : buffer.o

# target to build an object file
buffer.c.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/buffer.c.o
.PHONY : buffer.c.o

buffer.i: buffer.c.i

.PHONY : buffer.i

# target to preprocess a source file
buffer.c.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/buffer.c.i
.PHONY : buffer.c.i

buffer.s: buffer.c.s

.PHONY : buffer.s

# target to generate assembly for a file
buffer.c.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/buffer.c.s
.PHONY : buffer.c.s

socket_utils.o: socket_utils.c.o

.PHONY : socket_utils.o

# target to build an object file
socket_utils.c.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/socket_utils.c.o
.PHONY : socket_utils.c.o

socket_utils.i: socket_utils.c.i

.PHONY : socket_utils.i

# target to preprocess a source file
socket_utils.c.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/socket_utils.c.i
.PHONY : socket_utils.c.i

socket_utils.s: socket_utils.c.s

.PHONY : socket_utils.s

# target to generate assembly for a file
socket_utils.c.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/socket_utils.c.s
.PHONY : socket_utils.c.s

tcpservepollnonbET_RDHUB.o: tcpservepollnonbET_RDHUB.c.o

.PHONY : tcpservepollnonbET_RDHUB.o

# target to build an object file
tcpservepollnonbET_RDHUB.c.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/tcpservepollnonbET_RDHUB.c.o
.PHONY : tcpservepollnonbET_RDHUB.c.o

tcpservepollnonbET_RDHUB.i: tcpservepollnonbET_RDHUB.c.i

.PHONY : tcpservepollnonbET_RDHUB.i

# target to preprocess a source file
tcpservepollnonbET_RDHUB.c.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/tcpservepollnonbET_RDHUB.c.i
.PHONY : tcpservepollnonbET_RDHUB.c.i

tcpservepollnonbET_RDHUB.s: tcpservepollnonbET_RDHUB.c.s

.PHONY : tcpservepollnonbET_RDHUB.s

# target to generate assembly for a file
tcpservepollnonbET_RDHUB.c.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/tcpservepollnonbET_RDHUB.c.s
.PHONY : tcpservepollnonbET_RDHUB.c.s

utils.o: utils.c.o

.PHONY : utils.o

# target to build an object file
utils.c.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/utils.c.o
.PHONY : utils.c.o

utils.i: utils.c.i

.PHONY : utils.i

# target to preprocess a source file
utils.c.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/utils.c.i
.PHONY : utils.c.i

utils.s: utils.c.s

.PHONY : utils.s

# target to generate assembly for a file
utils.c.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/utils.c.s
.PHONY : utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... a.out"
	@echo "... agent.o"
	@echo "... agent.i"
	@echo "... agent.s"
	@echo "... buffer.o"
	@echo "... buffer.i"
	@echo "... buffer.s"
	@echo "... socket_utils.o"
	@echo "... socket_utils.i"
	@echo "... socket_utils.s"
	@echo "... tcpservepollnonbET_RDHUB.o"
	@echo "... tcpservepollnonbET_RDHUB.i"
	@echo "... tcpservepollnonbET_RDHUB.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

